---
title: "Raster Plot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Code for making raster plot of the button presses for Story Segmentation
Author: Cameron Perrin, cperrin@wustl.edu


#Plot one participant for one story

```{r, echo=FALSE,eval=TRUE, message= FALSE}
##Code for making raster plot of the button presses for Story Segmentation
#Author: Cameron Perrin, cperrin@wustl.edu
if(!require("dplyr")) install.packages("dplyr"); library(dplyr)
if(!require("ggplot2")) install.packages("ggplot2"); library(ggplot2)
if(!require("tidyverse")) install.packages("tidyverse");library(tidyverse)
if(!require("patchwork")) install.packages("patchwork");library(patchwork)

#load data
messy_data = read.csv("C:/Users/CKPer/Box/WashU/Peelle Lab/Story Segmentation/Online Sona data/gorilla data_long version/data_exp_15568-v3_task-j2vq.csv")
#want data for reaction time, for the space presses
messy_data = filter(messy_data, Response=="space")
reaction_time = select(messy_data, Participant.Private.ID, narrativeName, noiseCondition, Reaction.Time) #reaction time should be in ms, from the start of the story
#get rid of lecture practice data
reaction_time = filter(reaction_time, narrativeName!="Lecture1")

#try plotting pt 1268616 for Narrative 3
pt_1268618_N3 = filter(reaction_time, narrativeName=="Narrative3" & Participant.Private.ID=="1268616")
x0 = vector()
y0 = rep(0, nrow(pt_1268618_N3))
y1 = rep(1, nrow(pt_1268618_N3))
for(rt in pt_1268618_N3$Reaction.Time){
  x0 = c(x0, rt)
}
x0 = as.numeric(x0)
x0 = x0/1000 #convert to seconds from ms

plot(c(0, x0[length(x0)]), c(0,1), col = "white", xlab = "Time (seconds)", ylab = "", main = "Button Presses for pt 1268616, Narrative 3", axes=FALSE)
Axis(side=1, labels=TRUE)
segments(x0=x0, y0=y0, y1=y1)

```

#Plot multiple participants for one story

```{r, echo=FALSE,eval=TRUE, message= FALSE}
#plot for Narrative 3, in quiet
n3_quiet_long = filter(reaction_time, narrativeName=="Narrative3" & noiseCondition=="quiet")
n3_quiet = pivot_wider(select(n3_quiet_long, -noiseCondition), names_from = narrativeName, values_from = Reaction.Time, values_fn = list(Reaction.Time = list))
all_x0 = list()
for(pt in n3_quiet){
  x0 = vector()
  for(rt in n3_quiet$Narrative3[pt]){
    x0 = c(x0, rt)
  }
  x0 = as.numeric(x0)
  x0 = x0/1000 
  all_x0[[pt]] = x0 #wtf it works when I use a specific pt number tho
}

```



